Enhancement/#108 support dictionary aware parquet converters
exasol/cloud-storage-extension pull request #109
Opened 2020-11-16 13:21 UTC by morazow

Fixes #108.

2020-11-16 15:00 UTC, AnastasiiaSergienko requested changes
Looks good.Just a couple of comments

2020-11-17 06:45 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/parquet/converter/ConverterFactory.scala
> +   * If Parquet field is a complex datatype, then it is converted to the
Ahh yes, I started with support for complex types, I am going to work on it in separate branch.

2020-11-17 06:47 UTC, morazow commented on doc/user_guide/user_guide.md
> +| boolean        |                        | BOOLEAN                         |
Not really sorting. But I arranged them in groups:
- boolean
- ints
- longs
- custom types (decimal, date, timestamp)
- nested types

2020-11-17 07:09 UTC, AnastasiiaSergienko approved these changes

2020-11-17 07:19 UTC, merged