Add support for connections behind from behind proxy
exasol/cloud-storage-extension pull request #172
Opened 2021-09-16 21:51 UTC by baunz

Use the available functionality in hdfs storage implementations for GCP and S3

2021-09-21 07:34 UTC, morazow commented
Hey @baunz,

Thanks for the pull request! I am going to check it soon.

2021-09-22 08:09 UTC, morazow commented on doc/user_guide/user_guide.md
> +properties with the `%jvmoption`
Could you please add an example for Azure?

```
%jvmoption -DHTTPS_PROXY=http://username:password@10.10.1.10:1180
```

2021-09-22 08:14 UTC, morazow requested changes
I have added some minor editorial suggestions.

2021-09-22 08:14 UTC, morazow commented on doc/user_guide/user_guide.md
> +properties with the `%jvmoption`
```suggestion
properties using the `%jvmoption`  when creating deployment scripts.
```

2021-09-22 08:14 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
> +   *  Return the proxy host to use for the bucket
```suggestion
   *  Returns the proxy host to use for the bucket.
```

2021-09-22 08:14 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
> +   *  Return the proxy port to use for the bucket
```suggestion
   *  Returns the proxy port to use for the bucket.
```

2021-09-22 08:14 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
> +   *  Return the proxy port to use for the bucket
Please change other also.

2021-09-22 08:14 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
> +  /** An optional proxy host that needs to be used when accessing the bucket */
```suggestion
  /** An optional proxy host that needs to be used when accessing the bucket. */
```

2021-09-22 08:14 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
> +  /** An optional proxy host that needs to be used when accessing the bucket */
Change other also.

2021-09-23 06:03 UTC, baunz commented
Hi @morazow 

thanks for reviewing and fixing - I did not had time yesteray to go over your suggestions but will do this today!

2021-09-23 07:26 UTC, morazow commented
Hey @baunz,

Thanks a lot for the pull request! We are planning new release soon, it would be nice to have this also included.

2021-09-23 07:27 UTC, merged